# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - plantuml
    - wget
  jobs:
    post_install:
      - |
        [ -z "$PLANTUML_JAR_PATH" ] && {
          echo "ERROR: PLANTUML_JAR_PATH environment variable is not defined!"
          exit 1
        }
        wget https://github.com/plantuml/plantuml/releases/download/v1.2024.7/plantuml-1.2024.7.jar -O "$PLANTUML_JAR_PATH"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
